'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { motion } from 'framer-motion';
import { Bell, Boxes, ChartNoAxesCombined, GalleryVerticalEnd, Home, LayoutDashboard, Network, PackageSearch, ShoppingBag } from 'lucide-react';
import { cn } from '@/lib/utils';
const nav = [
  ['Landing','/',Home], ['Dashboard','/dashboard',LayoutDashboard], ['Products','/products',PackageSearch], ['Orders','/orders',Boxes], ['Storefront','/store',ShoppingBag], ['Architecture','/architecture',Network], ['Notifications','/notifications',Bell], ['Analytics','/analytics',ChartNoAxesCombined]
] as const;
export function AnimatedSidebar() { const pathname=usePathname(); return <aside className="sticky top-0 hidden h-screen w-72 shrink-0 border-r border-white/10 bg-slate-950/60 p-4 backdrop-blur-2xl lg:block"><motion.div initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} className="mb-8 flex items-center gap-3 rounded-3xl border border-cyan-300/20 bg-white/[.04] p-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-300/15 text-cyan-200"><GalleryVerticalEnd/></div><div><div className="font-semibold text-white">AstraCart</div><div className="text-xs text-slate-400">Enterprise Control Plane</div></div></motion.div><nav className="space-y-2">{nav.map(([label,href,Icon], i)=>{const active=pathname===href; return <Link key={href} href={href}><motion.div initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} transition={{delay:i*.04}} className={cn('group flex items-center gap-3 rounded-2xl px-4 py-3 text-sm transition', active ? 'bg-cyan-300/15 text-cyan-100 shadow-glow' : 'text-slate-400 hover:bg-white/[.05] hover:text-white')}><Icon size={18}/><span>{label}</span>{active && <motion.span layoutId="nav-pill" className="ml-auto h-2 w-2 rounded-full bg-cyan-300"/>}</motion.div></Link>})}</nav><div className="absolute bottom-4 left-4 right-4 rounded-3xl border border-fuchsia-300/20 bg-fuchsia-300/10 p-4 text-sm text-fuchsia-100"><div className="font-medium">Live SaaS Mode</div><p className="mt-1 text-xs text-fuchsia-100/70">Gateway, Redis limits, Celery workflows and PostgreSQL schemas.</p></div></aside> }
