import type { Notification, Order, Product, ServiceHealth } from './types';
export const revenueData = [
  { month: 'Jan', revenue: 180000, orders: 240 }, { month: 'Feb', revenue: 235000, orders: 318 }, { month: 'Mar', revenue: 312000, orders: 422 },
  { month: 'Apr', revenue: 428000, orders: 518 }, { month: 'May', revenue: 690000, orders: 811 }, { month: 'Jun', revenue: 820000, orders: 940 }
];
export const paymentData = [{ name: 'Success', value: 82 }, { name: 'Failed', value: 11 }, { name: 'Refunded', value: 7 }];
export const inventoryData = [{ day:'Mon', stock: 420 }, { day:'Tue', stock: 398 }, { day:'Wed', stock: 472 }, { day:'Thu', stock: 454 }, { day:'Fri', stock: 390 }, { day:'Sat', stock: 510 }, { day:'Sun', stock: 488 }];
export const products: Product[] = Array.from({ length: 18 }, (_, i) => ({ id: `prod-${i+1}`, title: ['Aurora Headphones','Nova Desk Lamp','Vanta Backpack','Quantum Keyboard','Pulse Running Shoes','Halo Travel Case'][i%6] + ` ${i+1}`, category: ['Electronics','Home Studio','Travel','Gaming','Fitness','Fashion'][i%6], price: 2999 + i*750, discount_price: i%3===0 ? 2499+i*600 : undefined, stock_quantity: [2,4,8,12,0,35,64][i%7], rating: 4 + ((i%10)/10), image: `https://images.unsplash.com/photo-${1500000000000+i*991}?auto=format&fit=crop&w=900&q=80`, status: i%5===0 ? 'LOW_STOCK' : 'ACTIVE', sku: `ASTRA-${String(i+1).padStart(4,'0')}` }));
export const orders: Order[] = Array.from({ length: 20 }, (_, i) => ({ id: `ORD-${1000+i}`, customer: ['Nia Sharma','Kabir Rao','Mira Kapoor','Arjun Mehta'][i%4], email: `customer${i}@astracart.dev`, total: 3499 + i*1120, status: ['PENDING','PAID','SHIPPED','DELIVERED','CONFIRMED'][i%5] as Order['status'], payment: ['INITIATED','SUCCESS','SUCCESS','SUCCESS','FAILED'][i%5] as Order['payment'], items: 1 + (i%4), timeline: ['Order created','Payment reviewed','Warehouse synced','Customer notified'] }));
export const notifications: Notification[] = Array.from({ length: 12 }, (_, i) => ({ id: `note-${i}`, title: ['Payment received','Order shipped','Low-stock alert','Refund processed'][i%4], message: 'AstraCart workflow event processed across services with audit-safe metadata.', read: i%3===0, event: ['PAYMENT_SUCCESSFUL','ORDER_SHIPPED','LOW_STOCK','REFUND_PROCESSED'][i%4], channel: ['IN_APP','EMAIL','SMS'][i%3], time: `${i+1}m ago` }));
export const serviceHealth: ServiceHealth[] = ['API Gateway','User Service','Product Service','Cart Service','Order Service','Payment Service','Notification Service','Redis','PostgreSQL','Celery Workers'].map((name, i) => ({ name, latency: `${18+i*7}ms`, healthy: i !== 7, cpu: 24+i*5, memory: 38+i*4 }));
export const activities = ['Seller Mira added 4 premium products','Payment webhook marked ORD-1012 as PAID','Low-stock rule detected 7 SKUs','Celery generated daily sales report','Support updated delayed order timeline','Gateway throttled 3 anonymous bursts'];
