'use client';
import { Activity, AlertTriangle, CreditCard, IndianRupee, Package, ShoppingCart, Users } from 'lucide-react';
import { ActivityFeed } from '@/components/ActivityFeed';
import { OrdersTable } from '@/components/DataTable';
import { GlassCard } from '@/components/GlassCard';
import { MetricCard } from '@/components/MetricCard';
import { ServiceHealthCard } from '@/components/ServiceHealthCard';
import { Shell } from '@/components/Shell';
import { OrderStatusChart, PaymentChart, RevenueChart } from '@/components/charts';
import { orders, serviceHealth } from '@/lib/mock-data';
export default function Dashboard(){ return <Shell title="Executive Dashboard" subtitle="Live commerce command center with revenue, order velocity, payment risk, inventory alerts and service health."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><MetricCard label="Total Revenue" value="₹82.4L" trend="18.2% vs last month" icon={IndianRupee}/><MetricCard label="Orders" value="9,418" trend="940 this month" icon={ShoppingCart} delay=.05/><MetricCard label="Active Users" value="28.7K" trend="3.4K sellers" icon={Users} delay=.1/><MetricCard label="Inventory" value="4,882" trend="17 low-stock" icon={Package} delay=.15/><MetricCard label="Failed Payments" value="31" trend="-8% improved" icon={CreditCard} delay=.2/></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_.8fr]"><GlassCard><div className="mb-4 flex items-center gap-2 text-white"><Activity className="text-cyan-200"/> Revenue + order velocity</div><RevenueChart/></GlassCard><GlassCard><div className="mb-4 text-white">Order status mix</div><OrderStatusChart/></GlassCard></div><div className="mt-4 grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><GlassCard><div className="mb-4 text-white">Payment success / failure</div><PaymentChart/></GlassCard><GlassCard><div className="mb-4 flex items-center gap-2 text-white"><AlertTriangle className="text-orange-200"/> Recent orders</div><OrdersTable orders={orders}/></GlassCard></div><div className="mt-4 grid gap-4 xl:grid-cols-[1fr_.75fr]"><GlassCard><h2 className="mb-4 text-xl font-semibold text-white">System health</h2><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-5">{serviceHealth.map(s=><ServiceHealthCard key={s.name} service={s}/>)}</div></GlassCard><GlassCard><h2 className="mb-4 text-xl font-semibold text-white">Activity feed</h2><ActivityFeed/></GlassCard></div></Shell> }
